### ISSUE TITLE
[Rollout] Missed helix-machines update ETAs breaking deployment build

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#949]
Due to issues generating the base images and getting the repo's build under control, we missed our 10/1 ETA to update a lot of the artifacts and queue definitions. This is breaking the production deployment build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2283360&view=results

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by missymessa** [comment]
I think these were fixed.

**Comment by riarenas** [comment]
These were not fixed. The production branch still has the hack.

**Comment by riarenas** [comment]
https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/azure-pipelines.yml&version=GBproduction&line=460&lineEnd=472&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by riarenas** [comment]
This has been fixed.
